# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG JUPYTERHUB_VERSION
FROM jupyterhub/jupyterhub-onbuild:$JUPYTERHUB_VERSION

# Install dockerspawner, dummy authenticator, postgres
RUN /usr/local/bin/pip install --no-cache-dir \
        jupyterhub-dummyauthenticator \
        jupyterhub-nativeauthenticator \
        dockerspawner \
        psycopg2-binary
